name:                k-means
version:             0.1.1.0
gitlab:              "https://github.com/oyiekeallen/K-Means.git"
license:             BSD3
author:              "Allen Oyieke"
maintainer:          "oyiekeallen@gmail.com"
copyright:           "2018 Allen Oyieke"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Gitlab at <https://github.com/oyiekeallen/K-Means.git#readme>

dependencies:
- base >= 4.7 && < 5
- clock
- random

library:
  source-dirs: src

executables:
  k-means-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - k-means

tests:
  k-means-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - k-means
